import type { SymbolCategory } from '../types';

export const SYMBOL_CATEGORIES: SymbolCategory[] = [
  {
    id: 'basic',
    name: 'Basic',
    nameAr: 'أساسي',
    symbols: [
      { latex: '\\frac{}{}', display: 'a/b', description: 'Fraction', descriptionAr: 'كسر' },
      { latex: '\\sqrt{}', display: '√', description: 'Square root', descriptionAr: 'جذر تربيعي' },
      { latex: '\\sqrt[]{}', display: 'ⁿ√', description: 'Nth root', descriptionAr: 'جذر من الدرجة n' },
      { latex: '^{}', display: 'xⁿ', description: 'Power/Exponent', descriptionAr: 'أس' },
      { latex: '_{}', display: 'xₙ', description: 'Subscript', descriptionAr: 'مؤشر سفلي' },
      { latex: '\\pi', display: 'π', description: 'Pi', descriptionAr: 'باي' },
      { latex: '\\infty', display: '∞', description: 'Infinity', descriptionAr: 'ما لا نهاية' },
      { latex: '\\pm', display: '±', description: 'Plus-minus', descriptionAr: 'زائد ناقص' },
      { latex: '\\cdot', display: '⋅', description: 'Multiplication dot', descriptionAr: 'ضرب' },
      { latex: '\\div', display: '÷', description: 'Division', descriptionAr: 'قسمة' },
      { latex: '\\neq', display: '≠', description: 'Not equal', descriptionAr: 'لا يساوي' },
      { latex: '\\approx', display: '≈', description: 'Approximately', descriptionAr: 'تقريباً' },
      { latex: '\\equiv', display: '≡', description: 'Equivalent', descriptionAr: 'مكافئ' },
      { latex: '\\propto', display: '∝', description: 'Proportional', descriptionAr: 'تناسبي' },
      { latex: '\\%', display: '%', description: 'Percent', descriptionAr: 'نسبة مئوية' },
    ]
  },
  {
    id: 'calculus',
    name: 'Calculus',
    nameAr: 'تفاضل وتكامل',
    symbols: [
      { latex: '\\frac{d}{dx}', display: 'd/dx', description: 'Derivative', descriptionAr: 'مشتقة' },
      { latex: '\\frac{dy}{dx}', display: 'dy/dx', description: 'Derivative y wrt x', descriptionAr: 'مشتقة y بالنسبة لـ x' },
      { latex: '\\frac{d^2}{dx^2}', display: 'd²/dx²', description: 'Second derivative', descriptionAr: 'مشتقة ثانية' },
      { latex: '\\int', display: '∫', description: 'Integral', descriptionAr: 'تكامل' },
      { latex: '\\int_{}^{}', display: '∫ₐᵇ', description: 'Definite integral', descriptionAr: 'تكامل محدود' },
      { latex: '\\oint', display: '∮', description: 'Contour integral', descriptionAr: 'تكامل محيطي' },
      { latex: '\\iint', display: '∬', description: 'Double integral', descriptionAr: 'تكامل مزدوج' },
      { latex: '\\iiint', display: '∭', description: 'Triple integral', descriptionAr: 'تكامل ثلاثي' },
      { latex: '\\lim_{x \\to }', display: 'lim', description: 'Limit', descriptionAr: 'نهاية' },
      { latex: '\\sum_{}^{}', display: 'Σ', description: 'Summation', descriptionAr: 'مجموع' },
      { latex: '\\prod_{}^{}', display: 'Π', description: 'Product', descriptionAr: 'جداء' },
      { latex: '\\partial', display: '∂', description: 'Partial derivative', descriptionAr: 'مشتقة جزئية' },
      { latex: '\\nabla', display: '∇', description: 'Nabla/Del', descriptionAr: 'نابلا' },
      { latex: '\\Delta', display: 'Δ', description: 'Delta (change)', descriptionAr: 'دلتا (تغير)' },
      { latex: '\\delta', display: 'δ', description: 'Delta (Dirac)', descriptionAr: 'دلتا ديراك' },
      { latex: '\\infty', display: '∞', description: 'Infinity', descriptionAr: 'ما لا نهاية' },
    ]
  },
  {
    id: 'algebra',
    name: 'Algebra',
    nameAr: 'جبر',
    symbols: [
      { latex: '\\sum_{i=1}^{n}', display: 'Σᵢⁿ', description: 'Summation', descriptionAr: 'مجموع' },
      { latex: '\\prod_{i=1}^{n}', display: 'Πᵢⁿ', description: 'Product', descriptionAr: 'جداء' },
      { latex: '\\binom{}{}', display: '(n k)', description: 'Binomial', descriptionAr: 'معامل ثنائي' },
      { latex: '\\log_{}', display: 'log', description: 'Logarithm', descriptionAr: 'لوغاريتم' },
      { latex: '\\ln', display: 'ln', description: 'Natural log', descriptionAr: 'لوغاريتم طبيعي' },
      { latex: '\\exp', display: 'exp', description: 'Exponential', descriptionAr: 'أسي' },
      { latex: '\\sin', display: 'sin', description: 'Sine', descriptionAr: 'جيب' },
      { latex: '\\cos', display: 'cos', description: 'Cosine', descriptionAr: 'جيب التمام' },
      { latex: '\\tan', display: 'tan', description: 'Tangent', descriptionAr: 'ظل' },
      { latex: '\\cot', display: 'cot', description: 'Cotangent', descriptionAr: 'ظل التمام' },
      { latex: '\\sec', display: 'sec', description: 'Secant', descriptionAr: 'قاطع' },
      { latex: '\\csc', display: 'csc', description: 'Cosecant', descriptionAr: 'قاطع التمام' },
      { latex: '\\arcsin', display: 'arcsin', description: 'Inverse sine', descriptionAr: 'قوس جيب' },
      { latex: '\\arccos', display: 'arccos', description: 'Inverse cosine', descriptionAr: 'قوس جيب التمام' },
      { latex: '\\arctan', display: 'arctan', description: 'Inverse tangent', descriptionAr: 'قوس ظل' },
      { latex: '\\sinh', display: 'sinh', description: 'Hyperbolic sine', descriptionAr: 'جيب زائدي' },
      { latex: '\\cosh', display: 'cosh', description: 'Hyperbolic cosine', descriptionAr: 'جيب تمام زائدي' },
      { latex: '\\tanh', display: 'tanh', description: 'Hyperbolic tangent', descriptionAr: 'ظل زائدي' },
      { latex: '\\forall', display: '∀', description: 'For all', descriptionAr: 'لكل' },
      { latex: '\\exists', display: '∃', description: 'Exists', descriptionAr: 'يوجد' },
      { latex: '\\in', display: '∈', description: 'Element of', descriptionAr: 'عنصر من' },
      { latex: '\\notin', display: '∉', description: 'Not element of', descriptionAr: 'ليس عنصراً من' },
      { latex: '\\subset', display: '⊂', description: 'Subset', descriptionAr: 'مجموعة جزئية' },
      { latex: '\\supset', display: '⊃', description: 'Superset', descriptionAr: 'مجموعة شاملة' },
      { latex: '\\cup', display: '∪', description: 'Union', descriptionAr: 'اتحاد' },
      { latex: '\\cap', display: '∩', description: 'Intersection', descriptionAr: 'تقاطع' },
      { latex: '\\emptyset', display: '∅', description: 'Empty set', descriptionAr: 'مجموعة فارغة' },
    ]
  },
  {
    id: 'matrices',
    name: 'Matrices',
    nameAr: 'مصفوفات',
    symbols: [
      { latex: '\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}', display: '(a b; c d)', description: 'Matrix', descriptionAr: 'مصفوفة' },
      { latex: '\\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix}', display: '[a b; c d]', description: 'Matrix brackets', descriptionAr: 'مصفوفة بأقواس' },
      { latex: '\\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix}', display: '|a b; c d|', description: 'Determinant', descriptionAr: 'محdeterminant' },
      { latex: '\\det', display: 'det', description: 'Determinant', descriptionAr: 'محdeterminant' },
      { latex: '\\tr', display: 'tr', description: 'Trace', descriptionAr: 'أثر' },
      { latex: '\\rank', display: 'rank', description: 'Rank', descriptionAr: 'رتبة' },
      { latex: '\\dim', display: 'dim', description: 'Dimension', descriptionAr: 'بعد' },
      { latex: '\\ker', display: 'ker', description: 'Kernel', descriptionAr: 'نواة' },
      { latex: '\\operatorname{adj}', display: 'adj', description: 'Adjoint', descriptionAr: 'مصفوفة ملحقة' },
      { latex: '\\operatorname{cof}', display: 'cof', description: 'Cofactor', descriptionAr: 'عامل مشترك' },
      { latex: '\\begin{pmatrix} 1 & 0 & 0 \\\\ 0 & 1 & 0 \\\\ 0 & 0 & 1 \\end{pmatrix}', display: 'I₃', description: 'Identity matrix', descriptionAr: 'مصفوفة الوحدة' },
      { latex: '\\lambda', display: 'λ', description: 'Eigenvalue', descriptionAr: 'قيمة ذاتية' },
    ]
  },
  {
    id: 'greek',
    name: 'Greek Letters',
    nameAr: 'حروف يونانية',
    symbols: [
      { latex: '\\alpha', display: 'α', description: 'Alpha', descriptionAr: 'ألفا' },
      { latex: '\\beta', display: 'β', description: 'Beta', descriptionAr: 'بيتا' },
      { latex: '\\gamma', display: 'γ', description: 'Gamma', descriptionAr: 'جاما' },
      { latex: '\\Gamma', display: 'Γ', description: 'Capital Gamma', descriptionAr: 'جاما كبيرة' },
      { latex: '\\delta', display: 'δ', description: 'Delta', descriptionAr: 'دلتا' },
      { latex: '\\Delta', display: 'Δ', description: 'Capital Delta', descriptionAr: 'دلتا كبيرة' },
      { latex: '\\epsilon', display: 'ε', description: 'Epsilon', descriptionAr: 'إبسلون' },
      { latex: '\\zeta', display: 'ζ', description: 'Zeta', descriptionAr: 'زيتا' },
      { latex: '\\eta', display: 'η', description: 'Eta', descriptionAr: 'إيتا' },
      { latex: '\\theta', display: 'θ', description: 'Theta', descriptionAr: 'ثيتا' },
      { latex: '\\Theta', display: 'Θ', description: 'Capital Theta', descriptionAr: 'ثيتا كبيرة' },
      { latex: '\\iota', display: 'ι', description: 'Iota', descriptionAr: 'أيوتا' },
      { latex: '\\kappa', display: 'κ', description: 'Kappa', descriptionAr: 'كابا' },
      { latex: '\\lambda', display: 'λ', description: 'Lambda', descriptionAr: 'لامبدا' },
      { latex: '\\Lambda', display: 'Λ', description: 'Capital Lambda', descriptionAr: 'لامبدا كبيرة' },
      { latex: '\\mu', display: 'μ', description: 'Mu', descriptionAr: 'مو' },
      { latex: '\\nu', display: 'ν', description: 'Nu', descriptionAr: 'نو' },
      { latex: '\\xi', display: 'ξ', description: 'Xi', descriptionAr: 'كسي' },
      { latex: '\\Xi', display: 'Ξ', description: 'Capital Xi', descriptionAr: 'كسي كبيرة' },
      { latex: '\\pi', display: 'π', description: 'Pi', descriptionAr: 'باي' },
      { latex: '\\Pi', display: 'Π', description: 'Capital Pi', descriptionAr: 'باي كبيرة' },
      { latex: '\\rho', display: 'ρ', description: 'Rho', descriptionAr: 'رو' },
      { latex: '\\sigma', display: 'σ', description: 'Sigma', descriptionAr: 'سيجما' },
      { latex: '\\Sigma', display: 'Σ', description: 'Capital Sigma', descriptionAr: 'سيجما كبيرة' },
      { latex: '\\tau', display: 'τ', description: 'Tau', descriptionAr: 'تاو' },
      { latex: '\\phi', display: 'φ', description: 'Phi', descriptionAr: 'فاي' },
      { latex: '\\Phi', display: 'Φ', description: 'Capital Phi', descriptionAr: 'فاي كبيرة' },
      { latex: '\\chi', display: 'χ', description: 'Chi', descriptionAr: 'كاي' },
      { latex: '\\psi', display: 'ψ', description: 'Psi', descriptionAr: 'بسي' },
      { latex: '\\Psi', display: 'Ψ', description: 'Capital Psi', descriptionAr: 'بسي كبيرة' },
      { latex: '\\omega', display: 'ω', description: 'Omega', descriptionAr: 'أوميغا' },
      { latex: '\\Omega', display: 'Ω', description: 'Capital Omega', descriptionAr: 'أوميغا كبيرة' },
    ]
  },
  {
    id: 'geometry',
    name: 'Geometry & Vectors',
    nameAr: 'هندسة ومتجهات',
    symbols: [
      { latex: '\\vec{}', display: 'v⃗', description: 'Vector', descriptionAr: 'متجه' },
      { latex: '\\hat{}', display: 'î', description: 'Unit vector', descriptionAr: 'متجه وحدة' },
      { latex: '\\cdot', display: '⋅', description: 'Dot product', descriptionAr: 'ضرب نقطي' },
      { latex: '\\times', display: '×', description: 'Cross product', descriptionAr: 'ضرب اتجاهي' },
      { latex: '\\angle', display: '∠', description: 'Angle', descriptionAr: 'زاوية' },
      { latex: '\\perp', display: '⊥', description: 'Perpendicular', descriptionAr: 'عمودي' },
      { latex: '\\parallel', display: '∥', description: 'Parallel', descriptionAr: 'توازي' },
      { latex: '\\cong', display: '≅', description: 'Congruent', descriptionAr: 'متطابق' },
      { latex: '\\sim', display: '∼', description: 'Similar', descriptionAr: 'متشابه' },
      { latex: '\\triangle', display: '△', description: 'Triangle', descriptionAr: 'مثلث' },
      { latex: '\\square', display: '□', description: 'Square', descriptionAr: 'مربع' },
      { latex: '\\circ', display: '°', description: 'Degrees', descriptionAr: 'درجات' },
      { latex: '\\overrightarrow{}', display: 'AB→', description: 'Vector AB', descriptionAr: 'متجه AB' },
      { latex: '\\overline{}', display: 'AB̄', description: 'Line segment', descriptionAr: 'قطعة مستقيمة' },
      { latex: '\\overset{\\frown}{}', display: 'arc', description: 'Arc', descriptionAr: 'قوس' },
      { latex: '\\nabla', display: '∇', description: 'Gradient', descriptionAr: 'تدرج' },
      { latex: '\\nabla \\cdot', display: '∇⋅', description: 'Divergence', descriptionAr: 'تباعد' },
      { latex: '\\nabla \\times', display: '∇×', description: 'Curl', descriptionAr: 'دوامة' },
      { latex: '\\nabla^2', display: '∇²', description: 'Laplacian', descriptionAr: 'لابلاس' },
    ]
  },
  {
    id: 'physics',
    name: 'Physics & Engineering',
    nameAr: 'فيزياء وهندسة',
    symbols: [
      { latex: '\\sum \\vec{F} = 0', display: 'ΣF=0', description: 'Equilibrium', descriptionAr: 'اتزان' },
      { latex: '\\vec{F} = m\\vec{a}', display: 'F=ma', description: 'Newton 2nd', descriptionAr: 'نيوتن الثانية' },
      { latex: '\\vec{\\tau} = \\vec{r} \\times \\vec{F}', display: 'τ=r×F', description: 'Torque', descriptionAr: 'عزم الدوران' },
      { latex: '\\vec{L} = \\vec{r} \\times \\vec{p}', display: 'L=r×p', description: 'Angular momentum', descriptionAr: 'زخم زاوي' },
      { latex: '\\frac{1}{2}mv^2', display: '½mv²', description: 'Kinetic energy', descriptionAr: 'طاقة حركية' },
      { latex: 'mgh', display: 'mgh', description: 'Potential energy', descriptionAr: 'طاقة وضع' },
      { latex: '\\vec{p} = m\\vec{v}', display: 'p=mv', description: 'Linear momentum', descriptionAr: 'زخم خطي' },
      { latex: '\\omega', display: 'ω', description: 'Angular velocity', descriptionAr: 'سرعة زاوية' },
      { latex: '\\alpha', display: 'α', description: 'Angular acceleration', descriptionAr: 'تسارع زاوي' },
      { latex: 'I', display: 'I', description: 'Moment of inertia', descriptionAr: 'عزم القصور الذاتي' },
      { latex: '\\mu', display: 'μ', description: 'Friction coefficient', descriptionAr: 'معامل احتكاك' },
      { latex: '\\sigma', display: 'σ', description: 'Stress', descriptionAr: 'إجهاد' },
      { latex: '\\epsilon', display: 'ε', description: 'Strain', descriptionAr: 'انفعال' },
      { latex: 'E = \\frac{\\sigma}{\\epsilon}', display: 'E=σ/ε', description: "Young's modulus", descriptionAr: 'معامل يونغ' },
      { latex: '\\rho', display: 'ρ', description: 'Density', descriptionAr: 'كثافة' },
      { latex: '\\eta', display: 'η', description: 'Viscosity', descriptionAr: 'لزوجة' },
      { latex: '\\Re', display: 'Re', description: 'Reynolds number', descriptionAr: 'عدد رينولدز' },
      { latex: '\\nabla \\cdot \\vec{E} = \\frac{\\rho}{\\epsilon_0}', display: '∇⋅E=ρ/ε₀', description: "Gauss's law", descriptionAr: 'قانون غاوس' },
      { latex: '\\nabla \\times \\vec{E} = -\\frac{\\partial \\vec{B}}{\\partial t}', display: '∇×E=-∂B/∂t', description: "Faraday's law", descriptionAr: 'قانون فاراداي' },
    ]
  },
  {
    id: 'inequalities',
    name: 'Inequalities & Relations',
    nameAr: 'متباينات وعلاقات',
    symbols: [
      { latex: '\\leq', display: '≤', description: 'Less than or equal', descriptionAr: 'أصغر من أو يساوي' },
      { latex: '\\geq', display: '≥', description: 'Greater than or equal', descriptionAr: 'أكبر من أو يساوي' },
      { latex: '\\ll', display: '≪', description: 'Much less than', descriptionAr: 'أصغر بكثير من' },
      { latex: '\\gg', display: '≫', description: 'Much greater than', descriptionAr: 'أكبر بكثير من' },
      { latex: '\\prec', display: '≺', description: 'Precedes', descriptionAr: 'يسبق' },
      { latex: '\\succ', display: '≻', description: 'Succeeds', descriptionAr: 'يلحق' },
      { latex: '\\preceq', display: '≼', description: 'Precedes or equal', descriptionAr: 'يسبق أو يساوي' },
      { latex: '\\succeq', display: '≽', description: 'Succeeds or equal', descriptionAr: 'يلحق أو يساوي' },
      { latex: '\\sim', display: '∼', description: 'Similar to', descriptionAr: 'مشابه لـ' },
      { latex: '\\simeq', display: '≃', description: 'Asymptotically equal', descriptionAr: 'متساوي تقريباً' },
      { latex: '\\approx', display: '≈', description: 'Approximately', descriptionAr: 'تقريباً' },
      { latex: '\\cong', display: '≅', description: 'Congruent', descriptionAr: 'متطابق' },
      { latex: '\\equiv', display: '≡', description: 'Equivalent', descriptionAr: 'مكافئ' },
      { latex: '\\propto', display: '∝', description: 'Proportional', descriptionAr: 'تناسبي' },
      { latex: '\\neq', display: '≠', description: 'Not equal', descriptionAr: 'لا يساوي' },
    ]
  },
  {
    id: 'arrows',
    name: 'Arrows & Logic',
    nameAr: 'أسهم ومنطق',
    symbols: [
      { latex: '\\rightarrow', display: '→', description: 'Right arrow', descriptionAr: 'سهم يمين' },
      { latex: '\\leftarrow', display: '←', description: 'Left arrow', descriptionAr: 'سهم يسار' },
      { latex: '\\Rightarrow', display: '⇒', description: 'Implies', descriptionAr: 'يتضمن' },
      { latex: '\\Leftarrow', display: '⇐', description: 'Implied by', descriptionAr: 'يتضمن من' },
      { latex: '\\Leftrightarrow', display: '⇔', description: 'If and only if', descriptionAr: 'إذا وفقط إذا' },
      { latex: '\\leftrightarrow', display: '↔', description: 'Equivalent', descriptionAr: 'مكافئ' },
      { latex: '\\mapsto', display: '↦', description: 'Maps to', descriptionAr: 'يُعين إلى' },
      { latex: '\\to', display: '→', description: 'To', descriptionAr: 'إلى' },
      { latex: '\\gets', display: '←', description: 'Gets', descriptionAr: 'يحصل على' },
      { latex: '\\uparrow', display: '↑', description: 'Up arrow', descriptionAr: 'سهم أعلى' },
      { latex: '\\downarrow', display: '↓', description: 'Down arrow', descriptionAr: 'سهم أسفل' },
      { latex: '\\Uparrow', display: '⇑', description: 'Double up', descriptionAr: 'سهم مزدوج أعلى' },
      { latex: '\\Downarrow', display: '⇓', description: 'Double down', descriptionAr: 'سهم مزدوج أسفل' },
      { latex: '\\nearrow', display: '↗', description: 'Nearrow', descriptionAr: 'سهم مائل' },
      { latex: '\\searrow', display: '↘', description: 'Searrow', descriptionAr: 'سهم مائل' },
      { latex: '\\wedge', display: '∧', description: 'And', descriptionAr: 'و' },
      { latex: '\\vee', display: '∨', description: 'Or', descriptionAr: 'أو' },
      { latex: '\\neg', display: '¬', description: 'Not', descriptionAr: 'ليس' },
      { latex: '\\top', display: '⊤', description: 'True', descriptionAr: 'صحيح' },
      { latex: '\\bot', display: '⊥', description: 'False', descriptionAr: 'خطأ' },
    ]
  },
  {
    id: 'accents',
    name: 'Accents & Decorations',
    nameAr: 'علامات وتزيين',
    symbols: [
      { latex: '\\bar{}', display: 'x̄', description: 'Bar', descriptionAr: 'شريط علوي' },
      { latex: '\\hat{}', display: 'x̂', description: 'Hat', descriptionAr: 'قبعة' },
      { latex: '\\tilde{}', display: 'x̃', description: 'Tilde', descriptionAr: 'تيلدا' },
      { latex: '\\dot{}', display: 'ẋ', description: 'Dot', descriptionAr: 'نقطة' },
      { latex: '\\ddot{}', display: 'ẍ', description: 'Double dot', descriptionAr: 'نقطتان' },
      { latex: '\\vec{}', display: 'v⃗', description: 'Vector arrow', descriptionAr: 'سهم متجه' },
      { latex: '\\overline{}', display: 'AB̄', description: 'Overline', descriptionAr: 'خط علوي' },
      { latex: '\\underline{}', display: 'x̲', description: 'Underline', descriptionAr: 'خط سفلي' },
      { latex: '\\widehat{}', display: 'ABĈ', description: 'Wide hat', descriptionAr: 'قبعة عريضة' },
      { latex: '\\widetilde{}', display: 'ABC̃', description: 'Wide tilde', descriptionAr: 'تيلدا عريضة' },
      { latex: '\\overbrace{}^{}', display: '⏞', description: 'Overbrace', descriptionAr: 'قوس علوي' },
      { latex: '\\underbrace{}_{}', display: '⏟', description: 'Underbrace', descriptionAr: 'قوس سفلي' },
      { latex: '\\overset{}{}', display: 'overset', description: 'Overset', descriptionAr: 'فوق' },
      { latex: '\\underset{}{}', display: 'underset', description: 'Underset', descriptionAr: 'تحت' },
      { latex: '\\boxed{}', display: '□', description: 'Boxed', descriptionAr: 'مربع' },
      { latex: '\\cancel{}', display: 'cancel', description: 'Cancel', descriptionAr: 'إلغاء' },
      { latex: '\\bcancel{}', display: 'bcancel', description: 'Backslash cancel', descriptionAr: 'إلغاء مائل' },
    ]
  },
];

export const getSymbolsByCategory = (categoryId: string) => {
  return SYMBOL_CATEGORIES.find(cat => cat.id === categoryId)?.symbols || [];
};

export const getAllSymbols = () => {
  return SYMBOL_CATEGORIES.flatMap(cat => cat.symbols);
};

export const searchSymbols = (query: string) => {
  const lowerQuery = query.toLowerCase();
  return getAllSymbols().filter(
    sym => 
      sym.description.toLowerCase().includes(lowerQuery) ||
      sym.descriptionAr.includes(lowerQuery) ||
      sym.latex.toLowerCase().includes(lowerQuery)
  );
};
